name: flutter_2048
description: 2048 Game built using AnimatedWidget and Explicit Animations.

version: 1.0.0+1

environment:
  sdk: ">3.0.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  uuid: ^3.0.6
  flutter_swipe_detector: ^2.0.0
  hive: ^2.1.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
